version: "3.9"
services: 
  product:
    build: ./product
    container_name: ecomm-product
  account:
    build: ./account
    container_name: ecomm-account
  mongo:
    image: mongo
    container_name: mongo-ecomm
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret